name: gke-run

on:
  push:
    branches:
      - master
      - main
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CLUSTER_ZONE: asia-southeast1-c
  REPO_NAME: testapp
  run_unit_test: dev

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      run: |
        npm install
    - name: Test and Generate Coverage
      if: ${{ env.run_unit_test == 'dev' }}
      run: |
        npm run coverage        
    # This step is where our service account will be authenticated
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Enable docker auth
      run: |-      
        gcloud --quiet auth configure-docker
    - name: Build and tag image
      run: |-
        docker build . --tag "gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
    - name: Install helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        
    - name: Deploy to GKE Cluster
      run: |-
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone $CLUSTER_ZONE
        # install/upgrade helm chart
        helm upgrade --install testapp ./helm/testapp --set image.repository=gcr.io/$PROJECT_ID/$REPO_NAME --set image.tag=$GITHUB_SHA
